### ISSUE TITLE
Actions on volumes by name instead of ID

### ISSUE THREAD

**Issue by omgimanerd** [phillbaker/digitalocean-node#11]
Will this be implemented in the future? Would you be open to accepting a pull request with this implemented?

**Comment by phillbaker** [comment]
I haven't started on this, a PR would be great!

**Comment by omgimanerd** [comment]
In the interest of backward-compatibility, I'll make the new methods:
* `client.volumes.getByName`
* `client.volumes.deleteByName`

It might take me a while to look through the codebase and understand it :)

**Comment by phillbaker** [comment]
Ah, so the `getByName` is actually just a variation on `list()`, it just accepts the name as a query param, similar to the listing images by types. That's documented here: https://github.com/phillbaker/digitalocean-node/#image-resource. So no need to implement a separate function for that one.
