### ISSUE TITLE
Renaming a tag doesn't return the new tag's JSON

### ISSUE THREAD

**Issue by omgimanerd** [phillbaker/digitalocean-node#16]
Renaming a tag should return the new tag according to the Digital Ocean documentation, but it returns the JSON object of the old tag. I suspect this is an error on their side.

On a completely unrelated note, I've published this: [doclt](https://www.npmjs.com/package/doclt)

**Comment by phillbaker** [comment]
Congrats on finishing it up! 

Hm, It might be worth opening an issue in https://github.com/digitalocean/api-v2/ and linking this one to it.

**Comment by phillbaker** [comment]
This was [deprecated by DO](https://developers.digitalocean.com/documentation/changelog/api-v2/deprecating-update-tag/) and removed from the client in 4fcd6e67616f60ea1f4c616551118b883cc7244f.
