### ISSUE TITLE
New Spaces API

### ISSUE THREAD

**Issue by ifvictr** [phillbaker/digitalocean-node#20]
Today, DigitalOcean officially launched Spaces, which is object storage. They also provided an API to interface with it. Could you add support for Spaces? Thanks!

Related reading:
- https://developers.digitalocean.com/documentation/spaces/
- https://www.digitalocean.com/community/tutorials/an-introduction-to-digitalocean-spaces

**Comment by phillbaker** [comment]
Hey there @ifvictr! Good news and bad news - the bad news is that spaces is a different schema at a different abstraction level (xml and actual file objects) than this api wrapper. The good news is that it's interopable with lots of existing s3 clients, here's one: https://github.com/andrewrk/node-s3-client.

You should be able to use spaces similarly to:

```
var s3 = require('s3');

var client = s3.createClient({
  s3Options: {
    accessKeyId: "your spaces key from https://cloud.digitalocean.com/settings/api/tokens",
    secretAccessKey: "your spaces secret from https://cloud.digitalocean.com/settings/api/tokens",
    region: "nyc3",
    endpoint: 'nyc3.digitaloceanspaces.com',
  },
});
```

If you'd like to try this out and add a note to the README explaining this, that'd be much appreciated!

**Comment by ifvictr** [comment]
I tried that, and it worked! Thanks, @phillbaker! I'll add this to the README some time later.
