### ISSUE TITLE
Error: Unexpected reponse code: 200

### ISSUE THREAD

**Issue by brad1121** [phillbaker/digitalocean-node#27]
`node_modules\digitalocean\lib\digitalocean\client.js:160:25`

When attempting to create a volume ( using client.volumes.create( {attrs} ) ) I'm getting the aforementioned error, which is actually a success. I can see the volume is created on DO.

Not sure why I'm getting a 200 response and not a 201 as per the docs, but in any case this should not cause the promise to fail.

Region I'm seeing this issue on is sgp1

**Comment by brad1121** [comment]
worked around it by simply changing line 36 of volume.js to
` return this.client.post('/volumes', attributes, [200,201], 'volume', callback);`

**Comment by phillbaker** [comment]
Looks like the right thing to do! Want to throw into a PR? Probably good to
leave a comment about the difference between the docs as well.
