### ISSUE TITLE
Missing: Listing Droplets by Tag

### ISSUE THREAD

**Issue by royalgarter** [phillbaker/digitalocean-node#4]
Ref: https://developers.digitalocean.com/documentation/v2/#listing-droplets-by-tag

**Comment by phillbaker** [comment]
@royalgarter you should be able to do this via:

```
var tag = 'foo';
client.droplets.list({ tag_name: tag }, callback)
```

See #1. Going to close this issue for now, but if there's a way we could improve the documentation or examples, please comment!
