### ISSUE TITLE
Implement snapshot fetching?

### ISSUE THREAD

**Issue by omgimanerd** [phillbaker/digitalocean-node#9]
The digitalocean api has snapshot fetching that's separate from image fetching. Will this be implemented?

**Comment by phillbaker** [comment]
Ah, thanks @omgimanerd, had some work on a branch to finish that up. I'll get that pushed and released in the next few days.

**Comment by omgimanerd** [comment]
Awesome! I'm working on a CLI for digital ocean that uses this package. Please give me a heads up when that's released :) Thanks very much

**Comment by omgimanerd** [comment]
Just a reminder, please bump the version and publish to npm. Thanks very much for the fix. :)

**Comment by phillbaker** [comment]
Whoops, sorry, thanks!
